In [5]:
from dataset import StarCraftMotionDataset, pad_collate_fn
from torch.utils.data import DataLoader, Dataset
import torch
import torch_scatter
import torch.nn as nn

criterion = nn.MSELoss(reduction='sum')

batch_size = 16

test_dataset = StarCraftMotionDataset("/local/scratch/a/bai116/datasets/StarCraftMotion_v0.2/processed", train=False)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, collate_fn=pad_collate_fn)

In [21]:
loss = 0
count = 0
for i, data in enumerate(test_loader):
    if i > 100:
        break
    data = torch.swapaxes(data, 1, 2)
    print(data[0,0,0,0])
    y = data[:, 2:, :, (2,3,7,8)] / 255
    y_pred = (2 * data[:, 1:-1, :, (2,3,7,8)] -  data[:, :-2, :, (2,3,7,8)]) / 255
#     print(y_pred.shape)
#     print(y.shape)
#     print(y.shape)
    print((y_pred-y).norm(dim=(2,3)))
    print("---")
#     print((y_pred-y).shape)
#     print((y_pred-y).norm(dim=(2,3)).shape)

tensor(79.)
tensor([[0.7574, 0.6548, 0.1560, 0.3194],
        [0.0351, 0.0396, 0.0400, 0.0366],
        [0.0323, 0.0340, 0.0349, 0.0346],
        [0.0266, 0.0254, 0.0319, 0.0299],
        [0.0248, 0.0266, 0.0269, 0.0254],
        [0.0171, 0.0188, 0.3694, 0.3693],
        [0.0368, 0.0337, 0.0357, 0.0344],
        [0.0291, 0.0285, 0.0288, 0.0306],
        [0.1252, 0.0319, 0.0277, 0.0314],
        [0.0200, 0.0192, 0.0175, 0.0188],
        [0.0218, 0.0208, 0.0222, 0.0196],
        [0.0171, 0.0175, 0.0162, 0.0192],
        [0.0211, 0.0208, 0.0208, 0.0215],
        [0.0157, 0.0196, 0.0196, 0.0188],
        [0.0340, 0.0704, 0.0579, 0.0661],
        [0.0232, 0.0235, 0.0248, 0.0232]])
---
tensor(120.)
tensor([[0.0337, 0.0355, 0.0351, 0.0319],
        [0.0386, 0.0413, 0.0366, 0.0364],
        [0.0218, 0.0204, 0.0245, 0.0218],
        [0.0192, 0.0175, 0.0184, 0.0162],
        [0.0451, 0.0440, 0.0421, 0.0451],
        [0.0533, 0.0516, 0.0494, 0.0487],
        [0.3314, 0.3313, 1.0500, 1.0530],
    

tensor(28.)
tensor([[0.0326, 0.0355, 0.0346, 0.0357],
        [0.0525, 0.0572, 0.0774, 0.0523],
        [0.0175, 0.0180, 0.0196, 0.0184],
        [0.0229, 0.0229, 0.0257, 0.0232],
        [0.0218, 0.0208, 0.0215, 0.0229],
        [0.0162, 0.1773, 0.0180, 0.1815],
        [0.0357, 0.0328, 0.0340, 0.0321],
        [0.0632, 0.0309, 0.0314, 0.0599],
        [0.0296, 0.0326, 0.0291, 0.0275],
        [0.0301, 0.0291, 0.0269, 0.0280],
        [0.0157, 0.0136, 0.0152, 0.0157],
        [0.0359, 0.0366, 1.4147, 1.4147],
        [0.1297, 0.4765, 0.4759, 0.1605],
        [0.0184, 0.0180, 0.0157, 0.0175],
        [0.0196, 0.0204, 0.0204, 0.0200],
        [0.0211, 0.0251, 0.0235, 0.0232]])
---
tensor(89.)
tensor([[0.0304, 0.0916, 1.2089, 1.2113],
        [0.0204, 0.0175, 0.0157, 0.0162],
        [0.0314, 0.0301, 0.0301, 0.0301],
        [0.0321, 0.0323, 0.0342, 0.0351],
        [0.1065, 0.0301, 0.1023, 0.1020],
        [1.2475, 0.1651, 0.4204, 0.6339],
        [0.0166, 0.0180, 0.0192, 0.0157],
     

tensor([[0.0229, 0.0225, 0.0211, 0.0215],
        [0.0111, 0.0104, 0.0078, 0.0088],
        [0.0245, 0.0263, 0.0299, 0.0306],
        [0.1729, 0.1686, 0.2329, 0.2376],
        [0.0180, 0.0225, 0.0184, 0.0192],
        [0.0141, 0.0157, 0.0162, 0.0162],
        [0.0316, 0.0323, 0.0330, 0.0309],
        [0.0550, 0.1963, 0.1907, 0.0480],
        [0.0175, 0.0180, 0.0196, 0.0188],
        [0.0232, 0.0192, 0.0208, 0.0184],
        [0.0326, 0.0306, 0.0316, 0.0326],
        [0.0180, 0.0157, 0.0166, 0.0175],
        [0.0147, 0.0157, 0.0175, 0.0171],
        [0.0346, 0.0351, 0.0314, 0.0333],
        [0.0319, 0.0346, 0.0330, 0.0333],
        [0.0260, 0.0218, 0.2032, 0.2030]])
---
tensor(55.)
tensor([[0.0136, 0.0152, 0.0141, 0.0096],
        [0.0260, 0.0260, 0.0269, 0.0254],
        [0.0055, 0.0475, 0.0475, 0.0078],
        [0.0211, 0.0184, 0.0215, 0.0204],
        [0.4952, 0.0204, 0.5533, 0.3066],
        [0.0357, 0.0326, 0.0335, 0.0353],
        [0.2287, 0.0538, 0.2301, 0.2276],
        [0.7398, 

tensor([[0.0472, 0.0215, 0.0245, 0.0494],
        [0.0319, 0.0344, 0.0346, 0.0357],
        [0.0304, 0.0291, 0.0285, 0.0299],
        [0.0242, 0.0272, 0.0239, 0.0263],
        [0.0280, 0.0222, 0.0242, 0.0272],
        [0.0272, 0.0275, 0.0280, 0.0304],
        [0.0400, 0.0374, 0.0366, 0.0454],
        [0.0411, 0.0438, 0.0437, 0.0402],
        [0.0316, 0.0311, 0.0291, 0.0306],
        [0.0304, 0.0260, 0.0275, 0.0288],
        [0.0152, 0.0068, 0.0055, 0.0068],
        [0.0171, 0.0157, 0.0171, 0.0200],
        [0.1021, 0.1419, 0.0926, 0.1120],
        [0.0251, 0.0272, 0.0239, 0.0266],
        [0.0479, 0.0494, 0.0513, 0.0545],
        [0.0248, 0.0301, 0.0285, 0.0269]])
---
tensor(79.)
tensor([[0.0364, 0.0349, 0.0362, 0.0340],
        [1.6450, 1.1839, 0.1956, 0.1145],
        [0.0519, 0.0638, 0.0328, 0.0304],
        [0.0513, 0.0516, 0.0516, 0.0574],
        [0.0316, 0.0340, 0.0301, 0.0280],
        [0.0184, 0.0188, 0.0162, 0.0192],
        [0.1352, 0.1352, 0.0235, 0.0242],
        [0.0520, 

In [3]:
print(y_pred_1[:,:,2:4].shape)

NameError: name 'y_pred_1' is not defined

In [5]:
print(unit_type_loss/unit_count)

tensor([6.3669e-03,        nan, 2.0013e-04, 0.0000e+00, 2.3832e-04, 0.0000e+00,
               nan, 2.7161e-04, 2.9458e-04, 0.0000e+00, 0.0000e+00, 3.0304e-04,
        2.9496e-04, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.4001e-05,
        1.5359e-04, 2.0792e-03, 5.5702e-04, 1.3873e-04, 0.0000e+00, 6.6085e-05,
               nan, 7.4782e-05, 3.3420e-04, 0.0000e+00, 1.8809e-04, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0023e-04,        nan, 1.7056e-04,
        0.0000e+00, 0.0000e+00, 8.3750e-04, 0.0000e+00, 0.0000e+00, 3.0223e-04,
        0.0000e+00, 1.1078e-04, 1.5953e-05, 1.2416e-04, 0.0000e+00, 0.0000e+00,
        3.1720e-05, 9.0478e-08, 4.0649e-06, 0.0000e+00, 0.0000e+00, 1.1644e-03,
        0.0000e+00, 1.4698e-07, 7.1133e-06, 2.8180e-04, 0.0000e+00, 1.5017e-07,
        4.9567e-06, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.9127e-04, 0.0000e+00,
               nan,        nan, 1.0017e-04, 1.7279e-04, 0.0000e+00, 5.9501e-05,
        7.8556e-06, 3.7453e-04, 4.5146e-

In [6]:
torch.load('data/results.pt')

tensor([2.7310,    nan, 2.6242, 2.6041, 2.6904, 2.5881,    nan, 2.6755, 3.2407,
        2.4808, 2.5963, 2.7399, 2.6973,    nan, 2.8447, 2.7150, 2.4910, 2.8696,
        2.9917, 2.9898, 2.9167, 2.4351, 2.5415, 2.4075,    nan, 2.6643, 2.6289,
        2.6075, 2.5180, 2.5711, 1.5685, 2.6946, 2.6322, 2.5503,    nan, 2.7031,
        2.4822, 2.2314,    nan, 2.3873, 2.6490, 2.2372, 2.4875, 2.6828, 2.0375,
        2.7751, 2.8268, 3.0615, 2.6544, 2.6871, 2.3323, 2.6627, 2.8026, 3.0375,
        3.0727, 2.6749, 2.0918, 2.5598, 2.8287, 2.7147, 3.1406, 2.6655, 2.6375,
        2.6639,    nan,    nan,    nan,    nan, 2.7131, 2.4641, 2.2313, 3.3255,
        2.9619, 2.7484, 2.7407, 2.8022, 2.7700, 2.7672,    nan, 2.5304, 2.8013,
        2.8555, 2.8099, 2.9920, 2.0831, 2.3450, 2.7365,    nan,    nan, 2.5832,
        2.6618, 2.5983, 2.8097, 2.7063, 1.8023, 2.7750, 2.7039, 2.7016, 2.6573,
        2.8888, 3.1702,    nan, 3.3259, 2.8596, 2.8266, 2.8446, 2.6928,    nan,
        2.5691, 2.3298, 2.7766,    nan, 